export const SET_INGREDIENT = "SET_INGREDIENT";
export const SET_ALL_INGREDIENTS = "SET_ALL_INGREDIENTS";
export const INGREDIENTS_UI_START_LOADING = "INGREDIENTS_UI_START_LOADING";
export const INGREDIENTS_UI_STOP_LOADING = "INGREDIENTS_UI_STOP_LOADING";

export const SET_ORDERS = "SET_ORDERS";
export const ORDERS_UI_START_LOADING = "ORDERS_UI_START_LOADING";
export const ORDERS_UI_STOP_LOADING = "ORDERS_UI_STOP_LOADING";

export const SET_TOKEN = "SET_TOKEN";

export const SET_USER = "SET_USER";
export const USER_UI_START_LOADING = "USER_UI_START_LOADING";
export const USER_UI_STOP_LOADING = "USER_UI_STOP_LOADING";
