export const SET_INGREDIENT = 'SET_INGREDIENT';
export const INGREDIENTS_UI_START_LOADING = 'INGREDIENTS_UI_START_LOADING';
export const INGREDIENTS_UI_STOP_LOADING = 'INGREDIENTS_UI_STOP_LOADING';
export const SET_ORDERS = 'SET_ORDERS';
export const ORDERS_UI_START_LOADING = 'ORDERS_UI_START_LOADING';
export const ORDERS_UI_STOP_LOADING = 'ORDERS_UI_STOP_LOADING';
export const SET_ALL_INGREDIENTS = 'SET_ALL_INGREDIENTS';


